### PR TITLE
PR: Add attribute to keep track of packages whose installation was actually requested when listing them

### LINKED ISSUE #17: Add package dependency attribute
Add attribute to packages to determine if it was requested by the user or is a package installed as a dependency of a requested package. This attribute needs to be added when listing packages of an environment

### PR DESCRIPTION
**Pull request by dalthviz**
Fixes #17

### CODE REVIEW

**Comment by ccordoba12** [comment]
> the only changes were adding == and removing the build information for packaging (since on the tests its version is changed but without specificing a build only the package version).

Ok, so packages without specific build information are the ones actually requested by the user?

**Comment by ccordoba12** [comment]
> No, with the changes here, the export env while only will list as dependencies packages that were requested to be installed

Ok, I think understood: so, the env file has the same format as before (with build info included). It just doesn't have all packages in the env, but only the ones directly installed by the user.

Is that correct?

**Comment by dalthviz** [comment]
More or less, with the changes here the export functionality doesn't have the packages that are dependencies of packages requested but also only shows version and build info of the packages if that info was added when a package was requested to be installed. Some examples:

### If you create an env and install there a package like `packaging` without providing further constraints:

* Create `test` env and install `packaging`
`env-manager -b=conda-like -en=test create --packages=packaging`

* Export `test` env
`env-manager -b=conda-like -en=test export environment.yml`

* Result

```yml
name: 
channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- packaging
```

### If you create an env and install there a package like `packaging` but with the constraint `=21.0`:

* Create `test-version` env and install `packaging` with specific version
`env-manager -b=conda-like -en=test-version create --packages=packaging=21.0`

* Export `test-version` env
`env-manager -b=conda-like test-version export environment.yml`

* Result

```yml
name:
channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- packaging=21.0
```

### If you create an env and install there a package like `packaging` but with the constraint `=21.0=pyhd8ed1ab_0`:

* Create `test-version-build` env and install `packaging` with specific version and build
`env-manager -b=conda-like -en=test-version-build create --packages=packaging=21.0=pyhd8ed1ab_0`

* Export `test-version-build` env
`env-manager -b=conda-like test-version-build export environment.yml`

* Result

```yml
name:
channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- packaging==21.0=pyhd8ed1ab_0
```

**Review by ccordoba12 — APPROVED** [review]
Thanks @dalthviz!

**Pull request merged**
